version: '3'
services:
    bank.api:
        build:
            context: .
            dockerfile: Dockerfile
        image: bank.api:v1
        ports:
            - 88:80
        volumes:
            - './:/var/www'
        depends_on:
            - bank.db
        links:
            - bank.db
        container_name: bank.api
    bank.db:
        image: mysql:5.7
        container_name: bank.db
        ports:
            - 3308:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'test@123'
            MYSQL_DATABASE: 'bank'
            MYSQL_USER: 'system'
            MYSQL_PASSWORD: 'test@123'